// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account(name, email)
  VALUES ($1, $2)
RETURNING
  id, active, name, email, household, created
`

type CreateAccountParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.Name,
		&i.Email,
		&i.Household,
		&i.Created,
	)
	return i, err
}
