// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: grocery_list_grocery.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addGroceryListGrocery = `-- name: AddGroceryListGrocery :one
INSERT INTO grocery_list_grocery(grocery_list, grocery, grocery_category, quantity, price)
  VALUES ($1, $2, $3, $4, $5)
RETURNING
  id, active, grocery_list, grocery, grocery_category, quantity, price, created
`

type AddGroceryListGroceryParams struct {
	GroceryList     uuid.UUID     `json:"grocery_list"`
	Grocery         uuid.UUID     `json:"grocery"`
	GroceryCategory uuid.NullUUID `json:"grocery_category"`
	Quantity        int16         `json:"quantity"`
	Price           string        `json:"price"`
}

func (q *Queries) AddGroceryListGrocery(ctx context.Context, arg AddGroceryListGroceryParams) (GroceryListGrocery, error) {
	row := q.db.QueryRowContext(ctx, addGroceryListGrocery,
		arg.GroceryList,
		arg.Grocery,
		arg.GroceryCategory,
		arg.Quantity,
		arg.Price,
	)
	var i GroceryListGrocery
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.GroceryList,
		&i.Grocery,
		&i.GroceryCategory,
		&i.Quantity,
		&i.Price,
		&i.Created,
	)
	return i, err
}

const deleteGroceryListGrocery = `-- name: DeleteGroceryListGrocery :one
DELETE FROM grocery_list_grocery
WHERE id = $1
RETURNING
  id, active, grocery_list, grocery, grocery_category, quantity, price, created
`

func (q *Queries) DeleteGroceryListGrocery(ctx context.Context, id uuid.UUID) (GroceryListGrocery, error) {
	row := q.db.QueryRowContext(ctx, deleteGroceryListGrocery, id)
	var i GroceryListGrocery
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.GroceryList,
		&i.Grocery,
		&i.GroceryCategory,
		&i.Quantity,
		&i.Price,
		&i.Created,
	)
	return i, err
}

const editGroceryListGrocery = `-- name: EditGroceryListGrocery :one
UPDATE
  grocery_list_grocery
SET
  grocery_list = $2,
  quantity = $3,
  price = $4
WHERE
  id = $1
  OR grocery = $1
RETURNING
  id, active, grocery_list, grocery, grocery_category, quantity, price, created
`

type EditGroceryListGroceryParams struct {
	ID          uuid.UUID `json:"id"`
	GroceryList uuid.UUID `json:"grocery_list"`
	Quantity    int16     `json:"quantity"`
	Price       string    `json:"price"`
}

func (q *Queries) EditGroceryListGrocery(ctx context.Context, arg EditGroceryListGroceryParams) (GroceryListGrocery, error) {
	row := q.db.QueryRowContext(ctx, editGroceryListGrocery,
		arg.ID,
		arg.GroceryList,
		arg.Quantity,
		arg.Price,
	)
	var i GroceryListGrocery
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.GroceryList,
		&i.Grocery,
		&i.GroceryCategory,
		&i.Quantity,
		&i.Price,
		&i.Created,
	)
	return i, err
}

const getAllGroceryListGroceries = `-- name: GetAllGroceryListGroceries :many
SELECT
  grocery_list_grocery.id, grocery_list_grocery.active, grocery_list_grocery.grocery_list, grocery_list_grocery.grocery, grocery_list_grocery.grocery_category, grocery_list_grocery.quantity, grocery_list_grocery.price, grocery_list_grocery.created,
  grocery_list.name AS grocery_list_name,
  grocery.name,
  grocery_category.name AS grocery_category_name
FROM
  grocery_list_grocery
  LEFT JOIN grocery ON grocery_list_grocery.grocery = grocery.id
  LEFT JOIN grocery_category ON grocery_list_grocery.grocery_category = grocery_category.id
  LEFT JOIN grocery_list ON grocery_list_grocery.grocery_list = grocery_list.id
WHERE
  grocery_list_grocery.active = TRUE
ORDER BY
  grocery_list_grocery.created DESC
`

type GetAllGroceryListGroceriesRow struct {
	ID                  uuid.UUID      `json:"id"`
	Active              bool           `json:"active"`
	GroceryList         uuid.UUID      `json:"grocery_list"`
	Grocery             uuid.UUID      `json:"grocery"`
	GroceryCategory     uuid.NullUUID  `json:"grocery_category"`
	Quantity            int16          `json:"quantity"`
	Price               string         `json:"price"`
	Created             time.Time      `json:"created"`
	GroceryListName     sql.NullString `json:"grocery_list_name"`
	Name                sql.NullString `json:"name"`
	GroceryCategoryName sql.NullString `json:"grocery_category_name"`
}

func (q *Queries) GetAllGroceryListGroceries(ctx context.Context) ([]GetAllGroceryListGroceriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroceryListGroceries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllGroceryListGroceriesRow{}
	for rows.Next() {
		var i GetAllGroceryListGroceriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Active,
			&i.GroceryList,
			&i.Grocery,
			&i.GroceryCategory,
			&i.Quantity,
			&i.Price,
			&i.Created,
			&i.GroceryListName,
			&i.Name,
			&i.GroceryCategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroceryListGroceries = `-- name: GetGroceryListGroceries :many
SELECT
  grocery_list_grocery.id, grocery_list_grocery.active, grocery_list_grocery.grocery_list, grocery_list_grocery.grocery, grocery_list_grocery.grocery_category, grocery_list_grocery.quantity, grocery_list_grocery.price, grocery_list_grocery.created,
  grocery_list.name AS grocery_list_name,
  grocery.name,
  grocery_category.name AS grocery_category_name
FROM
  grocery_list_grocery
  LEFT JOIN grocery ON grocery_list_grocery.grocery = grocery.id
  LEFT JOIN grocery_category ON grocery_list_grocery.grocery_category = grocery_category.id
  LEFT JOIN grocery_list ON grocery_list_grocery.grocery_list = grocery_list.id
WHERE
  grocery_list_grocery.active = TRUE
  AND grocery_list = $1
ORDER BY
  grocery_list_grocery.created DESC
`

type GetGroceryListGroceriesRow struct {
	ID                  uuid.UUID      `json:"id"`
	Active              bool           `json:"active"`
	GroceryList         uuid.UUID      `json:"grocery_list"`
	Grocery             uuid.UUID      `json:"grocery"`
	GroceryCategory     uuid.NullUUID  `json:"grocery_category"`
	Quantity            int16          `json:"quantity"`
	Price               string         `json:"price"`
	Created             time.Time      `json:"created"`
	GroceryListName     sql.NullString `json:"grocery_list_name"`
	Name                sql.NullString `json:"name"`
	GroceryCategoryName sql.NullString `json:"grocery_category_name"`
}

func (q *Queries) GetGroceryListGroceries(ctx context.Context, groceryList uuid.UUID) ([]GetGroceryListGroceriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroceryListGroceries, groceryList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroceryListGroceriesRow{}
	for rows.Next() {
		var i GetGroceryListGroceriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Active,
			&i.GroceryList,
			&i.Grocery,
			&i.GroceryCategory,
			&i.Quantity,
			&i.Price,
			&i.Created,
			&i.GroceryListName,
			&i.Name,
			&i.GroceryCategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
