// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: grocery_category.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addGroceryCategory = `-- name: AddGroceryCategory :one
INSERT INTO grocery_category(name)
  VALUES ($1)
RETURNING
  id, active, name, created
`

func (q *Queries) AddGroceryCategory(ctx context.Context, name string) (GroceryCategory, error) {
	row := q.db.QueryRowContext(ctx, addGroceryCategory, name)
	var i GroceryCategory
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.Name,
		&i.Created,
	)
	return i, err
}

const deleteGroceryCategory = `-- name: DeleteGroceryCategory :one
UPDATE
  grocery_category
SET
  active = NOT active
WHERE
  id = $1
RETURNING
  id, active, name, created
`

func (q *Queries) DeleteGroceryCategory(ctx context.Context, id uuid.UUID) (GroceryCategory, error) {
	row := q.db.QueryRowContext(ctx, deleteGroceryCategory, id)
	var i GroceryCategory
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.Name,
		&i.Created,
	)
	return i, err
}

const editGroceryCategory = `-- name: EditGroceryCategory :one
UPDATE
  grocery_category
SET
  name = $2
WHERE
  id = $1
RETURNING
  id, active, name, created
`

type EditGroceryCategoryParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) EditGroceryCategory(ctx context.Context, arg EditGroceryCategoryParams) (GroceryCategory, error) {
	row := q.db.QueryRowContext(ctx, editGroceryCategory, arg.ID, arg.Name)
	var i GroceryCategory
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.Name,
		&i.Created,
	)
	return i, err
}

const getGroceryCategories = `-- name: GetGroceryCategories :many
SELECT
  id, active, name, created
FROM
  grocery_category
WHERE
  active = TRUE
ORDER BY
  name DESC
`

func (q *Queries) GetGroceryCategories(ctx context.Context) ([]GroceryCategory, error) {
	rows, err := q.db.QueryContext(ctx, getGroceryCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroceryCategory{}
	for rows.Next() {
		var i GroceryCategory
		if err := rows.Scan(
			&i.ID,
			&i.Active,
			&i.Name,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
