// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID     `json:"id"`
	Active    bool          `json:"active"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Household uuid.NullUUID `json:"household"`
	Created   time.Time     `json:"created"`
}

type Category struct {
	ID      uuid.UUID `json:"id"`
	Active  bool      `json:"active"`
	Name    string    `json:"name"`
	Created time.Time `json:"created"`
}

type Grocery struct {
	ID              uuid.UUID     `json:"id"`
	Active          bool          `json:"active"`
	Name            string        `json:"name"`
	Category        uuid.NullUUID `json:"category"`
	DefaultQuantity int16         `json:"default_quantity"`
	DefaultPrice    string        `json:"default_price"`
	Created         time.Time     `json:"created"`
}

type GroceryList struct {
	ID      uuid.UUID `json:"id"`
	Active  bool      `json:"active"`
	Name    string    `json:"name"`
	Created time.Time `json:"created"`
}

type GroceryListGrocery struct {
	ID          uuid.UUID `json:"id"`
	Active      bool      `json:"active"`
	GroceryList uuid.UUID `json:"grocery_list"`
	Grocery     uuid.UUID `json:"grocery"`
	Quantity    int16     `json:"quantity"`
	Price       string    `json:"price"`
	Created     time.Time `json:"created"`
}

type Household struct {
	ID      uuid.UUID `json:"id"`
	Active  bool      `json:"active"`
	Name    string    `json:"name"`
	Created time.Time `json:"created"`
}
